services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/active-upstream.conf:/etc/nginx/conf.d/active-upstream.conf:ro
    networks:
      - front_net
      - back_net
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  front_net:
    external: true
    name: gym_front_network
  back_net:
    external: true
    name: gym_back_network
